// Auto-generated by scripts/generate_audio.js
// Run: node scripts/generate_audio.js
export const audioMap = {
  "Hello there, explorer! Today, we are going to learn about a very special shape — the SQUARE!": "/assets/audio/audio_hello_there_explorer_today_we__0.mp3",
  "Aanya looked at her window and noticed something. It had four sides... and they were ALL the same! Can you guess what shape that is?": "/assets/audio/audio_aanya_looked_at_her_window_and_1.mp3",
  "Look at this square. Let's count its sides together! One, two, three, FOUR sides!": "/assets/audio/audio_look_at_this_square_let_s_coun_2.mp3",
  "Now let's find the corners! One, two, three, FOUR corners! A square always has four corners.": "/assets/audio/audio_now_let_s_find_the_corners_one_3.mp3",
  "Here's the most important thing about a square — ALL its sides are EQUAL. They are the same length!": "/assets/audio/audio_here_s_the_most_important_thin_4.mp3",
  "Now it's YOUR turn! Drag the tiles onto the grid to build a square. Make sure all the sides match!": "/assets/audio/audio_now_it_s_your_turn_drag_the_ti_5.mp3",
  "Time to go on a shape hunt! Can you find all the squares hiding on the screen? Tap each one you find!": "/assets/audio/audio_time_to_go_on_a_shape_hunt_can_6.mp3",
  "Wonderful!": "/assets/audio/audio_wonderful__7.mp3",
  "Great job!": "/assets/audio/audio_great_job__8.mp3",
  "You got it!": "/assets/audio/audio_you_got_it__9.mp3",
  "Superstar!": "/assets/audio/audio_superstar__10.mp3",
  "That's right!": "/assets/audio/audio_that_s_right__11.mp3",
  "Amazing!": "/assets/audio/audio_amazing__12.mp3",
  "Great job! That's a square!": "/assets/audio/audio_great_job_that_s_a_square__13.mp3",
  "Oops, not quite! Let's try again.": "/assets/audio/audio_oops_not_quite_let_s_try_again_14.mp3",
  "Hmm, look carefully!": "/assets/audio/audio_hmm_look_carefully__15.mp3",
  "You can do it!": "/assets/audio/audio_you_can_do_it__16.mp3",
  "That's not a square, keep looking!": "/assets/audio/audio_that_s_not_a_square_keep_looki_17.mp3",
  "Hmm, check your sides!": "/assets/audio/audio_hmm_check_your_sides__18.mp3",
  "AMAZING! You are now a Square Expert! You learned that a square has 4 equal sides and 4 corners. Well done!": "/assets/audio/audio_amazing_you_are_now_a_square_e_19.mp3",
  "You made a square!": "/assets/audio/audio_you_made_a_square__20.mp3"
};
